SELECT * FROM SQLPLUS_PRODUCT_PROFILE;

SELECT * FROM GOODS;

CREATE TABLE "SYSTEM"."GOODS" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(512 BYTE), 
	"DESCRIPTION" VARCHAR2(2048 BYTE), 
	"PRICE" NUMBER(*,0), 
	"CATEGORY_ID" NUMBER(*,0)
   );
   
INSERT INTO "SYSTEM"."GOODS" (ID, NAME, DESCRIPTION, PRICE, CATEGORY_ID) VALUES ('5', 'SDD', 'SDDDD', '25', '3');

SELECT NAME, DESCRIPTION FROM GOODS;

SELECT NAME || DESCRIPTION  AS NAME_DESC FROM GOODS;

SELECT DISTINCT NAME FROM GOODS;

SELECT * FROM GOODS WHERE CATEGORY_ID=1;

SELECT * FROM GOODS WHERE ID IS NOT NULL;

SELECT * FROM GOODS WHERE CATEGORY_ID IN(1,3);

SELECT * FROM GOODS WHERE NAME LIKE 'f%';

SELECT * FROM GOODS WHERE NAME LIKE '_w%';

SELECT * FROM GOODS  ORDER BY NAME;

SELECT * FROM GOODS  ORDER BY NAME DESC;

SELECT UPPER (NAME) FROM GOODS;

SELECT LOWER (NAME) FROM GOODS;

SELECT ROUND (23.65896,2), TRUNC(23.65896,2), MOD(923,12) FROM DUAL;

SELECT SYSDATE FROM DUAL;









 
   
  