//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsForms_X_x_O.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        bool Login([System.ServiceModel.MessageParameterAttribute(Name="login")] string login1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllPlayerGame222", ReplyAction="http://tempuri.org/IService1/GetAllPlayerGame222Response")]
        string[] GetAllPlayerGame222(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllPlayerGame222", ReplyAction="http://tempuri.org/IService1/GetAllPlayerGame222Response")]
        System.Threading.Tasks.Task<string[]> GetAllPlayerGame222Async(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendCoord", ReplyAction="http://tempuri.org/IService1/SendCoordResponse")]
        void SendCoord(string Player, int Namber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendCoord", ReplyAction="http://tempuri.org/IService1/SendCoordResponse")]
        System.Threading.Tasks.Task SendCoordAsync(string Player, int Namber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendCoordOpponent", ReplyAction="http://tempuri.org/IService1/SendCoordOpponentResponse")]
        string[] SendCoordOpponent();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendCoordOpponent", ReplyAction="http://tempuri.org/IService1/SendCoordOpponentResponse")]
        System.Threading.Tasks.Task<string[]> SendCoordOpponentAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Win_Lose_Draw", ReplyAction="http://tempuri.org/IService1/Win_Lose_DrawResponse")]
        void Win_Lose_Draw(string login, string resultGame);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Win_Lose_Draw", ReplyAction="http://tempuri.org/IService1/Win_Lose_DrawResponse")]
        System.Threading.Tasks.Task Win_Lose_DrawAsync(string login, string resultGame);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllPlayerWin", ReplyAction="http://tempuri.org/IService1/GetAllPlayerWinResponse")]
        WcfServiceLibrary1.Player[] GetAllPlayerWin();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllPlayerWin", ReplyAction="http://tempuri.org/IService1/GetAllPlayerWinResponse")]
        System.Threading.Tasks.Task<WcfServiceLibrary1.Player[]> GetAllPlayerWinAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WindowsForms_X_x_O.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WindowsForms_X_x_O.ServiceReference1.IService1>, WindowsForms_X_x_O.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Login(string login1) {
            return base.Channel.Login(login1);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string login) {
            return base.Channel.LoginAsync(login);
        }
        
        public string[] GetAllPlayerGame222(string login) {
            return base.Channel.GetAllPlayerGame222(login);
        }
        
        public System.Threading.Tasks.Task<string[]> GetAllPlayerGame222Async(string login) {
            return base.Channel.GetAllPlayerGame222Async(login);
        }
        
        public void SendCoord(string Player, int Namber) {
            base.Channel.SendCoord(Player, Namber);
        }
        
        public System.Threading.Tasks.Task SendCoordAsync(string Player, int Namber) {
            return base.Channel.SendCoordAsync(Player, Namber);
        }
        
        public string[] SendCoordOpponent() {
            return base.Channel.SendCoordOpponent();
        }
        
        public System.Threading.Tasks.Task<string[]> SendCoordOpponentAsync() {
            return base.Channel.SendCoordOpponentAsync();
        }
        
        public void Win_Lose_Draw(string login, string resultGame) {
            base.Channel.Win_Lose_Draw(login, resultGame);
        }
        
        public System.Threading.Tasks.Task Win_Lose_DrawAsync(string login, string resultGame) {
            return base.Channel.Win_Lose_DrawAsync(login, resultGame);
        }
        
        public WcfServiceLibrary1.Player[] GetAllPlayerWin() {
            return base.Channel.GetAllPlayerWin();
        }
        
        public System.Threading.Tasks.Task<WcfServiceLibrary1.Player[]> GetAllPlayerWinAsync() {
            return base.Channel.GetAllPlayerWinAsync();
        }
    }
}
